# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c8f8caf6f85fa774df446c6172d02b5a"
name = "react-app"
handle = "react-app-121"
application_url = "https://allows-enhancing-india-merry.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "sziro.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://allows-enhancing-india-merry.trycloudflare.com/auth/callback",
  "https://allows-enhancing-india-merry.trycloudflare.com/auth/shopify/callback",
  "https://allows-enhancing-india-merry.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
